### ISSUE TITLE
Allow setting notifyProductionAPI

### ISSUE THREAD

**Issue by timarney** [alphagov/notifications-node-client#83]
Hi All

We're currently working on a 🇨🇦version of the Notify service.

**The problem:**

I recently did a test of the Node Client API and noticed the endpoint is hardcoded.

https://github.com/alphagov/notifications-node-client/blob/f0a34ffe26a33dcc0629f111a993db923f101e9d/client/api_client.js#L4

Ideally we would like to avoid creating `forks` of `all the client libraries` (the endpoint is also hardcoded in the other client libs I looked at).

**The ask:**

Wondering if you would accept a Pull Request which would allow that variable to be set via an environment variable while defaulting to your endpoint if that variable not available / set.

i.e. 
```
notifyProductionAPI = the_env_var || 'https://api.notifications.service.gov.uk'  
```

**Comment by quis** [comment]
Hey @timarney 👋 

All of our clients allow a different endpoint to be passed in when you instantiate them. For example the Node.js client lets you do this:

```javascript
var notifyClient = new NotifyClient('https://example.canada.ca', apiKey);
```

If an environment variable would work better for you then we’d be totally happy to accept a pull request though.

**Comment by timarney** [comment]
Thanks for the quick response @quis .

Perfect I see that in the [code](https://github.com/alphagov/notifications-node-client/blob/master/client/api_client.js#L27) now and and it will handle our needs 💯 .

<hr>

**Q:** Is that listed in the docs site some where? I found setup instructions [here](https://docs.notifications.service.gov.uk/node.html#install-the-client) that section doesn't mention setting the base url.

<hr>
<img width="834" alt="Screen Shot 2019-07-19 at 12 21 40 PM" src="https://user-images.githubusercontent.com/62242/61550278-0caf4800-aa20-11e9-9b47-0c101e4e7391.png">

**Comment by quis** [comment]
We don’t document that parameter because we didn’t anticipate people outside our team needing to use it (and therefore don’t want to distract them). The reason it’s there in the first place is because we run automated tests against a non-production environment, which lives on a different domain.

I’m going to close this now because I think you’ve got what you need. But anything else we can help with, let us know. You can also reach us via https://www.notifications.service.gov.uk/support if you have a question that doesn’t directly relate to one repository or another.
